// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckCsdbConnection(arg1:main.CsdbCredentials):Promise<main.CsdbConnectionStatus>;

export function CreateAnnotation(arg1:main.AnnotationHighlight):Promise<void>;

export function CreateBookmark(arg1:main.Bookmark):Promise<main.Bookmark>;

export function DeleteAnnotationById(arg1:string):Promise<void>;

export function DeleteBookmark(arg1:string):Promise<void>;

export function DeleteNoteById(arg1:string):Promise<void>;

export function GetAnnotations():Promise<Array<main.AnnotationHighlight>>;

export function GetAnnotationsByDMcode(arg1:string):Promise<Array<main.AnnotationHighlight>>;

export function GetCsdbPublications():Promise<Array<main.CsdbPublication>>;

export function InsertNote(arg1:main.Note):Promise<void>;

export function RetrieveAllBookmark():Promise<Array<main.Bookmark>>;

export function RetrieveAnnotationAndNotes():Promise<Array<main.Note>>;

export function RetrieveBookmark(arg1:number):Promise<main.Bookmark>;

export function RetrieveByDMCodeAndText(arg1:string,arg2:string):Promise<main.Note>;

export function RetrieveNotesById(arg1:string):Promise<main.Note>;

export function Shutdown():Promise<void>;

export function UpdateBookmark(arg1:main.Bookmark):Promise<main.Bookmark>;
