// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCsdbConnection(arg1) {
  return window['go']['main']['App']['CheckCsdbConnection'](arg1);
}

export function CreateAnnotation(arg1) {
  return window['go']['main']['App']['CreateAnnotation'](arg1);
}

export function CreateBookmark(arg1) {
  return window['go']['main']['App']['CreateBookmark'](arg1);
}

export function DeleteAnnotationById(arg1) {
  return window['go']['main']['App']['DeleteAnnotationById'](arg1);
}

export function DeleteBookmark(arg1) {
  return window['go']['main']['App']['DeleteBookmark'](arg1);
}

export function DeleteNoteById(arg1) {
  return window['go']['main']['App']['DeleteNoteById'](arg1);
}

export function GetAnnotations() {
  return window['go']['main']['App']['GetAnnotations']();
}

export function GetAnnotationsByDMcode(arg1) {
  return window['go']['main']['App']['GetAnnotationsByDMcode'](arg1);
}

export function GetCsdbPublications() {
  return window['go']['main']['App']['GetCsdbPublications']();
}

export function InsertNote(arg1) {
  return window['go']['main']['App']['InsertNote'](arg1);
}

export function RetrieveAllBookmark() {
  return window['go']['main']['App']['RetrieveAllBookmark']();
}

export function RetrieveAnnotationAndNotes() {
  return window['go']['main']['App']['RetrieveAnnotationAndNotes']();
}

export function RetrieveBookmark(arg1) {
  return window['go']['main']['App']['RetrieveBookmark'](arg1);
}

export function RetrieveByDMCodeAndText(arg1, arg2) {
  return window['go']['main']['App']['RetrieveByDMCodeAndText'](arg1, arg2);
}

export function RetrieveNotesById(arg1) {
  return window['go']['main']['App']['RetrieveNotesById'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function UpdateBookmark(arg1) {
  return window['go']['main']['App']['UpdateBookmark'](arg1);
}
